-- Pre-installed blueprints (the ones that ship inside the BPX mod) and a Download Y/N switch.
-- Applied 2026-09-28 as migration bp_preinstalled_downloadable.
--   downloadable  general switch: bp_download refuses (and does not count) a row that is off
--   preinstalled  the card reads 'Pre-installed with BPX' instead of offering a download
-- The rows themselves are generated by the mod repo's tools/seed_site_builtins.py (author
-- 'BPX Default', blueprint_id 'bpx-default-*', each with an owner record nobody holds).
alter table public.bp_blueprints add column if not exists downloadable boolean not null default true;
alter table public.bp_blueprints add column if not exists preinstalled boolean not null default false;

create or replace function public.bp_download(p_id bigint)
 returns text language plpgsql security definer set search_path to 'public'
as $function$
declare
  v_content text;
begin
  update public.bp_blueprints
     set downloads = downloads + 1
   where id = p_id and downloadable
   returning content into v_content;
  return v_content;
end;
$function$;

-- bp_list: adds 'downloadable' and 'preinstalled' to each card, and orders pre-installed
-- ones after the uploads (official desc, preinstalled asc, created_at desc).
